databases:
  - name: sample_chatapp_db
    databaseName: sample_chatapp_db
    user: sample_chatapp_db_user
    region: singapore

services:
  - type: web
    name: sample_chatapp_db
    env: ruby
    region: singapore
    plan: free
    # buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_chatapp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

